import { getPayload } from 'payload'
import configPromise from '@payload-config'
import { callModel } from '../openrouter-client'
import { extractTextFromLexical } from '../embeddings/lexical-text'
import { buildContext } from './context-builder'
import { markdownToLexical } from './lexical-utils'
import { loadVoiceForContentType, invalidateVoiceCache } from '../voice/loader'
import { buildVoicePrompt } from '../voice/prompt-builder'
import type {
  HandleMessageOptions,
  ConversationResponse,
  ConversationAction,
  ConversationContext,
} from './types'

// Stage transition maps (matching batch route)
const ARTICLE_ADVANCE: Record<string, string> = {
  idea: 'brief',
  brief: 'research',
  research: 'draft',
  draft: 'review',
  review: 'published',
}

const PAGE_ADVANCE: Record<string, string> = {
  idea: 'draft',
  draft: 'review',
  review: 'published',
}

function isValidTransition(
  currentStage: string,
  newStage: string,
  contentType: string,
): boolean {
  const isPage =
    contentType === 'destination_page' || contentType === 'property_page'
  const map = isPage ? PAGE_ADVANCE : ARTICLE_ADVANCE
  return map[currentStage] === newStage
}

// Parsed action from model response (looser than ConversationAction)
interface ParsedAction {
  type: string
  field?: string
  value?: string
  sectionName?: string
  index?: number
  question?: string
  answer?: string
  newStage?: string
  // update_voice fields
  operation?: string
  phrase?: string
  reason?: string
  alternative?: string
  excerpt?: string
  context?: string
  pattern?: string
  explanation?: string
  principle?: string
  example?: string
}

const ALLOWED_FIELDS = [
  'metaTitle',
  'metaDescription',
  'answerCapsule',
  'briefSummary',
  'targetAngle',
  'competitiveNotes',
]

// Map tab names to the fields/content they display, so the model knows
// what the designer is looking at and which fields to target
const TAB_CONTEXT: Record<string, string> = {
  Brief:
    'The Brief tab shows: briefSummary, targetAngle, targetAudience, competitiveNotes. When the designer asks about content on this tab, use edit_field targeting these fields.',
  Research:
    'The Research tab shows: the research synthesis, sources list, uncertainty map, and editorial notes. These are READ-ONLY in the workspace — they are generated by the research compiler. If the designer asks to change research formatting or content, explain that research is generated by the compiler and suggest running research again, or discuss what changes they want for the next research compilation. Do NOT edit briefSummary or other Brief fields when discussing research content.',
  Draft:
    'The Draft tab shows: the article body (for articles) or sections (for destination/property pages), plus metaTitle, metaDescription, answerCapsule. When editing, target body/sections or meta fields.',
  FAQ: 'The FAQ tab shows the FAQ items. Use edit_faq actions to modify them.',
  Distribution:
    'The Distribution tab shows: linkedinSummary, facebookSummary, facebookPinnedComment. These are not in the ALLOWED_FIELDS for edit_field — respond conversationally about distribution content.',
  Metadata:
    'The Metadata tab shows read-only project metadata. No editable fields here.',
  Images:
    'The Images tab shows the Image Library picker. The designer can browse, filter, and select hero images for this project. They can also generate new wildlife, landscape, destination, or country images using AI. Property/accommodation images cannot be generated — only scraped property images are used to ensure accuracy. When the designer asks about images, help them find relevant images or suggest generating new ones based on the project context.',
}

async function buildSystemPrompt(ctx: ConversationContext, activeTab?: string): Promise<string> {
  const parts: string[] = []

  parts.push(
    `You are Kiuli, a content assistant for a luxury African safari travel company. You are collaborating with a travel designer on a content project.`,
  )

  // Load and inject brand voice context
  const voice = await loadVoiceForContentType(ctx.contentType)
  const voicePrompt = buildVoicePrompt(voice)
  if (voicePrompt) {
    parts.push(`\n${voicePrompt}`)
  }

  // Active tab context — tell the model what the designer is looking at
  if (activeTab && TAB_CONTEXT[activeTab]) {
    parts.push(`\nDESIGNER CONTEXT: The designer is currently viewing the "${activeTab}" tab.`)
    parts.push(TAB_CONTEXT[activeTab])
    parts.push(
      `IMPORTANT: When the designer references "this content", "the formatting", "this section" etc., they are referring to what is displayed on the ${activeTab} tab. Do not modify fields from other tabs unless the designer explicitly names them.`,
    )
  }

  parts.push(`\nPROJECT:
Title: ${ctx.title}
Type: ${ctx.contentType}
Stage: ${ctx.stage}
Destinations: ${ctx.destinations?.join(', ') || 'Not specified'}
Properties: ${ctx.properties?.join(', ') || 'Not specified'}`)

  if (ctx.briefSummary || ctx.targetAngle || ctx.competitiveNotes) {
    parts.push(`\nBRIEF:`)
    if (ctx.briefSummary) parts.push(`Summary: ${ctx.briefSummary}`)
    if (ctx.targetAngle) parts.push(`Angle: ${ctx.targetAngle}`)
    if (ctx.competitiveNotes)
      parts.push(`Competitive notes: ${ctx.competitiveNotes}`)
  }

  if (ctx.synthesisText) {
    parts.push(`\nRESEARCH SYNTHESIS:\n${ctx.synthesisText}`)
    if (ctx.sourcesSummary) parts.push(`\nSources:\n${ctx.sourcesSummary}`)
  }

  if (ctx.draftText) {
    parts.push(`\nCURRENT DRAFT:\n${ctx.draftText}`)
  } else if (ctx.sections && Object.keys(ctx.sections).length > 0) {
    parts.push(`\nCURRENT SECTIONS:`)
    for (const [name, text] of Object.entries(ctx.sections)) {
      parts.push(`\n### ${name}\n${text}`)
    }
  }

  if (ctx.faqItems && ctx.faqItems.length > 0) {
    parts.push(`\nFAQ:`)
    for (const faq of ctx.faqItems) {
      parts.push(`Q: ${faq.question}\nA: ${faq.answer}`)
    }
  }

  if (ctx.metaTitle) parts.push(`\nMeta Title: ${ctx.metaTitle}`)
  if (ctx.metaDescription)
    parts.push(`Meta Description: ${ctx.metaDescription}`)
  if (ctx.answerCapsule) parts.push(`Answer Capsule: ${ctx.answerCapsule}`)

  if (ctx.relatedContent) {
    parts.push(
      `\nRELATED KIULI CONTENT (for consistency):\n${ctx.relatedContent}`,
    )
  }

  if (ctx.activeDirectives) {
    parts.push(
      `\nEDITORIAL DIRECTIVES (you must respect these):\n${ctx.activeDirectives}`,
    )
  }

  parts.push(`\n---

You can respond naturally to the designer. When they request changes to the content, include structured actions in your response.

RESPONSE FORMAT:
Always respond with a JSON object (and NOTHING else — no markdown fences, no preamble):

{
  "message": "Your natural language response to the designer",
  "actions": [],
  "suggestedNextStep": "Optional suggestion for what to do next"
}

AVAILABLE ACTIONS:

1. edit_field — Edit a simple text/textarea field
   { "type": "edit_field", "field": "metaTitle" | "metaDescription" | "answerCapsule" | "briefSummary" | "targetAngle" | "competitiveNotes", "value": "new text" }

2. edit_body — Rewrite the full article body (for articles)
   { "type": "edit_body", "value": "Full new body text in markdown format" }

3. edit_section — Edit a specific section (for compound types: destination_page, property_page)
   { "type": "edit_section", "sectionName": "overview" | "when_to_visit" | "why_choose" | "key_experiences" | "getting_there" | "health_safety" | "investment_expectation" | "top_lodges" | "faq", "value": "New section content" }

4. edit_faq — Replace an FAQ item or add a new one
   { "type": "edit_faq", "index": 0, "question": "...", "answer": "..." }
   { "type": "edit_faq", "index": -1, "question": "...", "answer": "..." }  // -1 means append new

5. stage_change — Advance or move the project to a different stage
   { "type": "stage_change", "newStage": "review" }
   Only suggest stage changes when the designer explicitly asks (e.g., "advance to review", "this looks good, move it forward")

6. update_voice — Update the Kiuli brand voice configuration (the global voice that shapes ALL future content)
   { "type": "update_voice", "operation": "add_banned_phrase", "phrase": "...", "reason": "...", "alternative": "..." }
   { "type": "update_voice", "operation": "add_gold_standard", "excerpt": "...", "context": "..." }
   { "type": "update_voice", "operation": "add_anti_pattern", "pattern": "...", "explanation": "..." }
   { "type": "update_voice", "operation": "add_principle", "principle": "...", "explanation": "...", "example": "..." }
   { "type": "update_voice", "operation": "update_summary", "value": "..." }

   CRITICAL: Only use update_voice when the designer explicitly talks about how Kiuli should write IN GENERAL — not about this specific content.
   "Kiuli should never say 'nestled'" → add_banned_phrase (this is about all future content)
   "This paragraph is perfect, save this voice" → add_gold_standard (this is about Kiuli's taste)
   "Make this warmer" → NO update_voice (that's about this specific content, use edit actions)
   "We should always lead with specifics" → add_principle (this is a general writing rule)

RULES:
- Only include actions when the designer requests a change. Conversational messages (questions, feedback, discussion) need no actions.
- When editing, show the specific change in your message ("I've updated the meta title to: ...").
- Respect all editorial directives. If a designer request would violate a directive, explain why and suggest an alternative.
- Be specific about safari destinations, properties, and wildlife. Use your knowledge of the project context.
- Keep meta titles under 60 characters. Keep meta descriptions under 160 characters. Keep answer capsules between 50-70 words.
- All content must follow the Kiuli voice identity, principles, and banned phrases listed above.
- Do NOT use emojis in any field values. Keep content professional and clean.
- briefSummary should be 2-3 concise sentences describing the article's scope. Never dump research content into the brief.
- When using update_voice, confirm the change to the designer and explain that it will affect all future Kiuli content.`)

  return parts.join('\n')
}

function parseModelResponse(raw: string): {
  message: string
  actions: ParsedAction[]
  suggestedNextStep?: string
} {
  let text = raw.trim()

  // Strip markdown fences if present
  if (text.startsWith('```')) {
    text = text.replace(/^```(?:json)?\s*\n?/, '').replace(/\n?```\s*$/, '')
  }

  try {
    const parsed = JSON.parse(text)
    return {
      message: parsed.message || text,
      actions: Array.isArray(parsed.actions) ? parsed.actions : [],
      suggestedNextStep: parsed.suggestedNextStep,
    }
  } catch {
    // Model returned non-JSON — treat as plain message
    return { message: raw, actions: [] }
  }
}

function validateAction(action: ParsedAction): boolean {
  if (!action.type) return false

  switch (action.type) {
    case 'edit_field':
      return (
        typeof action.field === 'string' && typeof action.value === 'string'
      )
    case 'edit_body':
      return typeof action.value === 'string'
    case 'edit_section':
      return (
        typeof action.sectionName === 'string' &&
        typeof action.value === 'string'
      )
    case 'edit_faq':
      return (
        typeof action.index === 'number' &&
        typeof action.question === 'string' &&
        typeof action.answer === 'string'
      )
    case 'stage_change':
      return typeof action.newStage === 'string'
    case 'update_voice':
      return typeof action.operation === 'string' && validateVoiceAction(action)
    default:
      return false
  }
}

function validateVoiceAction(action: ParsedAction): boolean {
  switch (action.operation) {
    case 'add_banned_phrase':
      return typeof action.phrase === 'string' && typeof action.reason === 'string'
    case 'add_gold_standard':
      return typeof action.excerpt === 'string' && typeof action.context === 'string'
    case 'add_anti_pattern':
      return typeof action.pattern === 'string' && typeof action.explanation === 'string'
    case 'add_principle':
      return typeof action.principle === 'string' && typeof action.explanation === 'string'
    case 'update_summary':
      return typeof action.value === 'string'
    default:
      return false
  }
}

/**
 * Process update_voice actions — writes directly to BrandVoice global.
 * Returns ConversationActions for the log.
 */
async function processVoiceActions(
  actions: ParsedAction[],
): Promise<ConversationAction[]> {
  const voiceActions = actions.filter((a) => a.type === 'update_voice')
  if (voiceActions.length === 0) return []

  const payload = await getPayload({ config: configPromise })
  // Cast through unknown — brand-voice slug not yet in generated Payload types
  const brandVoice = (await payload.findGlobal({ slug: 'brand-voice' as 'header' })) as unknown as Record<string, unknown>

  const appliedActions: ConversationAction[] = []

  for (const action of voiceActions) {
    try {
      const updateData: Record<string, unknown> = {}

      switch (action.operation) {
        case 'add_banned_phrase': {
          const existing = Array.isArray(brandVoice.bannedPhrases) ? [...brandVoice.bannedPhrases] : []
          existing.push({
            phrase: action.phrase,
            reason: action.reason,
            alternative: action.alternative || null,
          })
          updateData.bannedPhrases = existing
          appliedActions.push({
            type: 'update_voice',
            details: { operation: 'add_banned_phrase', phrase: action.phrase },
          })
          break
        }

        case 'add_gold_standard': {
          const existing = Array.isArray(brandVoice.goldStandard) ? [...brandVoice.goldStandard] : []
          existing.push({
            excerpt: action.excerpt,
            contentType: 'general',
            context: action.context,
            addedAt: new Date().toISOString(),
          })
          updateData.goldStandard = existing
          appliedActions.push({
            type: 'update_voice',
            details: { operation: 'add_gold_standard', context: action.context },
          })
          break
        }

        case 'add_anti_pattern': {
          const existing = Array.isArray(brandVoice.antiPatterns) ? [...brandVoice.antiPatterns] : []
          existing.push({
            pattern: action.pattern,
            explanation: action.explanation,
          })
          updateData.antiPatterns = existing
          appliedActions.push({
            type: 'update_voice',
            details: { operation: 'add_anti_pattern', pattern: action.pattern },
          })
          break
        }

        case 'add_principle': {
          const existing = Array.isArray(brandVoice.principles) ? [...brandVoice.principles] : []
          existing.push({
            principle: action.principle,
            explanation: action.explanation,
            example: action.example || null,
          })
          updateData.principles = existing
          appliedActions.push({
            type: 'update_voice',
            details: { operation: 'add_principle', principle: action.principle },
          })
          break
        }

        case 'update_summary': {
          updateData.voiceSummary = action.value
          appliedActions.push({
            type: 'update_voice',
            before: String(brandVoice.voiceSummary || '').substring(0, 200),
            after: String(action.value).substring(0, 200),
            details: { operation: 'update_summary' },
          })
          break
        }
      }

      if (Object.keys(updateData).length > 0) {
        // Append to evolution log
        const existingLog = Array.isArray(brandVoice.evolutionLog) ? [...brandVoice.evolutionLog] : []
        existingLog.push({
          date: new Date().toISOString(),
          change: describeVoiceChange(action),
          reason: `Designer requested via conversation`,
          source: 'designer_conversation',
        })
        updateData.evolutionLog = existingLog

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        await (payload.updateGlobal as any)({
          slug: 'brand-voice',
          data: updateData,
        })

        // Invalidate cache so subsequent reads get fresh data
        invalidateVoiceCache()
      }
    } catch (err) {
      console.error(`[conversation] Voice update failed:`, action, err)
    }
  }

  return appliedActions
}

function describeVoiceChange(action: ParsedAction): string {
  switch (action.operation) {
    case 'add_banned_phrase':
      return `Added banned phrase: "${action.phrase}"`
    case 'add_gold_standard':
      return `Added gold standard example: ${action.context}`
    case 'add_anti_pattern':
      return `Added anti-pattern: "${action.pattern}"`
    case 'add_principle':
      return `Added principle: "${action.principle}"`
    case 'update_summary':
      return `Updated voice summary`
    default:
      return `Voice update: ${action.operation}`
  }
}

/**
 * Process non-voice actions and accumulate all DB changes into a single data object.
 * NO individual payload.update calls — everything is batched into one write.
 */
function processProjectActions(
  project: Record<string, unknown>,
  actions: ParsedAction[],
): { data: Record<string, unknown>; appliedActions: ConversationAction[] } {
  const data: Record<string, unknown> = {}
  const appliedActions: ConversationAction[] = []

  // Filter out update_voice actions — those are handled separately
  const projectActions = actions.filter((a) => a.type !== 'update_voice')

  for (const action of projectActions) {
    try {
      switch (action.type) {
        case 'edit_field': {
          if (!ALLOWED_FIELDS.includes(action.field!)) {
            console.warn(
              `[conversation] Rejected edit to disallowed field: ${action.field}`,
            )
            continue
          }
          const before = (project[action.field!] as string) || ''
          data[action.field!] = action.value
          appliedActions.push({
            type: 'edit_field',
            field: action.field,
            before: before.substring(0, 200),
            after: (action.value as string).substring(0, 200),
          })
          break
        }

        case 'edit_body': {
          const beforeText = project.body
            ? extractTextFromLexical(project.body).substring(0, 200)
            : ''
          const lexicalBody = markdownToLexical(action.value!)
          data.body = lexicalBody
          appliedActions.push({
            type: 'edit_field',
            field: 'body',
            before: beforeText,
            after: (action.value as string).substring(0, 200),
          })
          break
        }

        case 'edit_section': {
          // Build from previously accumulated sections data, or from project
          const baseSections = (data.sections as Record<string, unknown>) ||
            (typeof project.sections === 'string'
              ? JSON.parse((project.sections as string) || '{}')
              : ((project.sections as Record<string, unknown>) || {}))
          const before = baseSections[action.sectionName!] || ''
          const beforeStr =
            typeof before === 'string'
              ? before
              : extractTextFromLexical(before)
          baseSections[action.sectionName!] = action.value
          data.sections = baseSections
          appliedActions.push({
            type: 'rewrite_section',
            sectionName: action.sectionName,
            before: beforeStr.substring(0, 200),
            after: (action.value as string).substring(0, 200),
          })
          break
        }

        case 'edit_faq': {
          // Build from previously accumulated FAQ data, or from project
          const baseFaq = (data.faqSection as Record<string, unknown>[]) ||
            (Array.isArray(project.faqSection)
              ? [...(project.faqSection as Record<string, unknown>[])]
              : [])
          if (action.index === -1) {
            baseFaq.push({
              question: action.question,
              answer: action.answer,
            })
          } else if (action.index! >= 0 && action.index! < baseFaq.length) {
            baseFaq[action.index!] = {
              question: action.question,
              answer: action.answer,
            }
          }
          data.faqSection = baseFaq
          appliedActions.push({
            type: 'edit_field',
            field: `faqSection[${action.index}]`,
            after: `Q: ${action.question}`.substring(0, 200),
          })
          break
        }

        case 'stage_change': {
          const currentStage = project.stage as string
          const contentType = project.contentType as string
          if (isValidTransition(currentStage, action.newStage!, contentType)) {
            data.stage = action.newStage
            data.processingStatus = 'idle'
            data.processingError = null
            data.processingStartedAt = null
            if (action.newStage === 'published') {
              data.publishedAt = new Date().toISOString()
            }
            appliedActions.push({
              type: 'stage_change',
              before: currentStage,
              after: action.newStage,
            })
          } else {
            console.warn(
              `[conversation] Invalid stage transition: ${currentStage} → ${action.newStage} for ${contentType}`,
            )
          }
          break
        }
      }
    } catch (err) {
      console.error(`[conversation] Action processing failed:`, action, err)
    }
  }

  return { data, appliedActions }
}

export async function handleMessage(
  options: HandleMessageOptions,
): Promise<ConversationResponse> {
  const { projectId, message, activeTab } = options

  // 1. Build context
  const ctx = await buildContext({ projectId })

  // 2. Format system prompt + conversation history
  const systemPrompt = await buildSystemPrompt(ctx, activeTab)

  const messages: Array<{
    role: 'system' | 'user' | 'assistant'
    content: string
  }> = [{ role: 'system', content: systemPrompt }]

  // Add recent conversation history
  for (const msg of ctx.recentMessages) {
    messages.push({
      role: msg.role === 'designer' ? 'user' : 'assistant',
      content: msg.content,
    })
  }

  // Add current message
  messages.push({ role: 'user', content: message })

  // 3. Call OpenRouter
  const result = await callModel('editing', messages, {
    maxTokens: 4096,
    temperature: 0.4,
  })

  // 4. Parse response
  const parsed = parseModelResponse(result.content)

  // 5. Validate actions
  const validActions = parsed.actions.filter((a) => {
    if (!validateAction(a)) {
      console.warn('[conversation] Invalid action discarded:', a)
      return false
    }
    return true
  })

  // 6. Process voice actions first (write to BrandVoice global)
  const voiceAppliedActions = await processVoiceActions(validActions)

  const payload = await getPayload({ config: configPromise })

  // Re-fetch project for fresh state
  const project = (await payload.findByID({
    collection: 'content-projects',
    id: projectId,
    depth: 0,
  })) as unknown as Record<string, unknown>

  // 7. Process project actions into a data object (NO individual DB writes)
  const { data: actionData, appliedActions: projectAppliedActions } =
    validActions.some((a) => a.type !== 'update_voice')
      ? processProjectActions(project, validActions)
      : { data: {}, appliedActions: [] }

  const allAppliedActions = [...projectAppliedActions, ...voiceAppliedActions]

  // 8. Build messages
  const designerMessage = {
    role: 'designer' as const,
    content: message,
    timestamp: new Date().toISOString(),
  }

  const kiuliMessage = {
    role: 'kiuli' as const,
    content: parsed.message,
    timestamp: new Date().toISOString(),
    actions: allAppliedActions.length > 0 ? allAppliedActions : undefined,
    suggestedNextStep: parsed.suggestedNextStep || undefined,
  }

  const currentMessages = Array.isArray(project.messages)
    ? [...(project.messages as Record<string, unknown>[])]
    : []
  currentMessages.push(designerMessage)
  currentMessages.push(kiuliMessage)

  // 9. ONE payload.update — field changes + messages combined
  await payload.update({
    collection: 'content-projects',
    id: projectId,
    data: {
      ...actionData,
      messages: currentMessages,
    },
  })

  return {
    message: parsed.message,
    actions: allAppliedActions,
    suggestedNextStep: parsed.suggestedNextStep,
  }
}
