/**
 * EVIDENCE 13: Auto-generated TypeScript Types for Inquiry
 *
 * Source: src/payload-types.ts (lines 2270-2342)
 * Generated by: Payload CMS
 * Timestamp: 2026-01-30
 *
 * These types are automatically generated by Payload when the dev server
 * starts or when `npm run build` is executed. They provide full TypeScript
 * support for the Inquiries collection.
 */

export interface Inquiry {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  phoneCountryCode: string;
  destinations: {
    code: string;
    id?: string | null;
  }[];
  timingType: 'specific' | 'flexible' | 'exploring';
  travelDateStart?: string | null;
  travelDateEnd?: string | null;
  /**
   * Format: YYYY-MM
   */
  travelWindowEarliest?: string | null;
  /**
   * Format: YYYY-MM
   */
  travelWindowLatest?: string | null;
  partyType: 'solo' | 'couple' | 'family' | 'multigenerational' | 'friends' | 'multiple_families' | 'other';
  totalTravelers: number;
  childrenCount: number;
  primaryInterest:
    | 'migration'
    | 'gorillas'
    | 'luxury_camp'
    | 'big_cats'
    | 'walking'
    | 'celebration'
    | 'ultimate'
    | 'other';
  budgetRange: '15k-25k' | '25k-40k' | '40k-60k' | '60k-80k' | '80k-100k' | '100k+' | 'unsure';
  /**
   * Budget midpoint in cents
   */
  statedBudgetCents: number;
  /**
   * 20% of stated budget
   */
  projectedProfitCents: number;
  howHeard: 'google' | 'ai' | 'referral' | 'advisor' | 'press' | 'social' | 'podcast' | 'returning' | 'other';
  message?: string | null;
  marketingConsent?: boolean | null;
  sessionId?: string | null;
  /**
   * Google Click ID
   */
  gclid?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  utmContent?: string | null;
  utmTerm?: string | null;
  referrer?: string | null;
  landingPage?: string | null;
  pageUrl?: string | null;
  /**
   * If submitted from an itinerary page
   */
  itinerarySlug?: string | null;
  hubspotContactId?: string | null;
  hubspotDealId?: string | null;
  inquiryType: 'form' | 'phone' | 'email' | 'chat';
  status: 'new' | 'contacted' | 'qualified' | 'converted' | 'lost';
  assignedDesigner?: string | null;
  formStartedAt?: string | null;
  timeToCompleteSeconds?: number | null;
  updatedAt: string;
  createdAt: string;
}

/**
 * Field Count Summary:
 * - Required fields: 15
 * - Optional fields: 21
 * - Total fields: 36 (including id, createdAt, updatedAt)
 *
 * Select Field Options:
 * - timingType: 3 options
 * - partyType: 7 options
 * - primaryInterest: 8 options
 * - budgetRange: 7 options
 * - howHeard: 9 options
 * - inquiryType: 4 options
 * - status: 5 options
 */
