import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

/**
 * Seeds the 80 launch itinerary targets from the Kiuli iTrvl Itinerary Briefing.
 * Odd numbers = Set A, Even numbers = Set B.
 * Primary itineraries are Google Ads landing pages — build first.
 */

interface Target {
  number: number
  name: string
  priority: 'primary' | 'secondary'
  set: 'A' | 'B'
  duration: string
  countries: string
  seasonality: string
  category: string
  experienceDescription: string
  propertyGuidance: string
  seoKeywords: string
}

const targets: Target[] = [
  // === SET A (odd numbers) ===
  { number: 1, name: 'Ultimate Great Migration: Serengeti to Mara', priority: 'primary', set: 'A', duration: '10–14 nights', countries: 'Tanzania, Kenya', seasonality: 'June–October', category: 'migration', experienceDescription: 'The full migration circuit — from calving grounds through river crossings. Multiple camps tracking the herds north. Helicopter transfers between key positions. Concludes in the Masai Mara for the dramatic river crossings.', propertyGuidance: 'Ultra-luxury mobile and permanent camps positioned along migration route. Mix of intimate mobile camps (6-8 tents) with established luxury lodges.', seoKeywords: 'great migration safari, serengeti to masai mara safari' },
  { number: 3, name: 'Mara River Crossing Experience', priority: 'primary', set: 'A', duration: '7–10 nights', countries: 'Kenya', seasonality: 'July–October', category: 'migration', experienceDescription: 'Focused on the most dramatic wildlife spectacle on earth — wildebeest river crossings in the Masai Mara. Strategic positioning near key crossing points. Extended game drives during peak activity.', propertyGuidance: 'Camps with proven proximity to crossing points. Private conservancy access essential for exclusivity.', seoKeywords: 'masai mara river crossing, wildebeest crossing safari' },
  { number: 5, name: 'Migration by Helicopter', priority: 'primary', set: 'A', duration: '8–12 nights', countries: 'Tanzania, Kenya', seasonality: 'June–October', category: 'migration', experienceDescription: 'Helicopter-supported migration tracking — covering more ground, accessing remote concentrations, aerial photography of the herds. A fundamentally different perspective on the migration.', propertyGuidance: 'Properties that support or partner with helicopter operators. Mix of remote fly-camps and luxury lodges.', seoKeywords: 'helicopter safari africa, luxury migration safari' },
  { number: 7, name: 'Rwanda Gorilla & Golden Monkey', priority: 'primary', set: 'A', duration: '5–7 nights', countries: 'Rwanda', seasonality: 'Year-round (Jun–Sep driest)', category: 'gorilla_primate', experienceDescription: 'Intimate primate encounters — mountain gorilla trekking in Volcanoes National Park plus golden monkey tracking. Cultural immersion in Kigali. Nyungwe Forest option for chimpanzees.', propertyGuidance: 'Ultra-luxury lodges near Volcanoes NP. Kigali boutique hotel for city component.', seoKeywords: 'rwanda gorilla safari, gorilla trekking luxury' },
  { number: 9, name: 'Ultimate Primate Safari: Rwanda & Uganda', priority: 'primary', set: 'A', duration: '10–14 nights', countries: 'Rwanda, Uganda', seasonality: 'Jun–Sep, Dec–Feb', category: 'gorilla_primate', experienceDescription: 'All great apes in one journey — gorillas in Rwanda, chimpanzees and gorillas in Uganda. Tree-climbing lions in Ishasha. Boat safaris on the Kazinga Channel.', propertyGuidance: 'Best available in both countries. Uganda has fewer luxury options — choose the best of what exists.', seoKeywords: 'gorilla safari rwanda uganda, primate safari africa' },
  { number: 11, name: 'Private Gorilla Experience', priority: 'primary', set: 'A', duration: '4–6 nights', countries: 'Rwanda', seasonality: 'Year-round', category: 'gorilla_primate', experienceDescription: 'The most exclusive gorilla experience possible — private vehicle, private guide, premium gorilla permits. Designed for those who want intimacy and exclusivity above all.', propertyGuidance: 'Single ultra-luxury property. The best room category. Private dining experiences.', seoKeywords: 'private gorilla trekking, exclusive gorilla safari' },
  { number: 13, name: 'Botswana Delta Honeymoon', priority: 'primary', set: 'A', duration: '7–10 nights', countries: 'Botswana', seasonality: 'May–October', category: 'honeymoon', experienceDescription: 'The ultimate romantic safari — mokoro glides through lily-pad channels, private island picnics, star beds under African skies. Combines water and land safari for variety.', propertyGuidance: 'Intimate camps (6-10 rooms). Private plunge pools essential. Star bed options. Honeymoon suites.', seoKeywords: 'botswana honeymoon safari, okavango delta honeymoon' },
  { number: 15, name: 'Tanzania & Indian Ocean Honeymoon', priority: 'primary', set: 'A', duration: '10–14 nights', countries: 'Tanzania', seasonality: 'Jun–Oct (safari), year-round (beach)', category: 'honeymoon', experienceDescription: 'Bush-to-beach romance — Serengeti or Ngorongoro wildlife combined with Zanzibar or mainland beach. Dramatic contrast between safari adventure and Indian Ocean relaxation.', propertyGuidance: 'Ultra-luxury safari lodge followed by exclusive beach property. Zanzibar or Mozambique coast.', seoKeywords: 'tanzania honeymoon safari, safari and beach honeymoon' },
  { number: 17, name: 'Kenya Family Adventure', priority: 'primary', set: 'A', duration: '8–12 nights', countries: 'Kenya', seasonality: 'Jul–Oct, Dec–Mar', category: 'family', experienceDescription: 'Kenya through young eyes — conservation education, junior ranger programs, Maasai cultural visits, camel rides, and incredible wildlife. Designed for families with children 6+.', propertyGuidance: 'Family-friendly camps with dedicated family suites/tents. Properties with kids programs. Private conservancies for flexibility.', seoKeywords: 'kenya family safari, family safari africa' },
  { number: 19, name: 'Tanzania Family Migration', priority: 'primary', set: 'A', duration: '8–12 nights', countries: 'Tanzania', seasonality: 'Jun–Oct', category: 'family', experienceDescription: 'The great migration experienced as a family — age-appropriate education about the ecosystem, tracking herds, understanding predator-prey dynamics. Ngorongoro Crater as a natural classroom.', propertyGuidance: 'Family suites or interconnecting tents. Properties that welcome children and have family-specific programming.', seoKeywords: 'tanzania family safari, family migration safari' },
  { number: 21, name: 'Botswana & Victoria Falls', priority: 'primary', set: 'A', duration: '8–11 nights', countries: 'Botswana, Zimbabwe', seasonality: 'May–October', category: 'classic', experienceDescription: 'Two of Southern Africa\'s greatest attractions in one journey — Okavango Delta water and land safaris combined with the thundering Victoria Falls. Chobe riverfront game viewing.', propertyGuidance: 'Premium Delta camps plus luxury Victoria Falls accommodation. Chobe option for river safari.', seoKeywords: 'botswana victoria falls safari, okavango delta and victoria falls' },
  { number: 23, name: 'Private Botswana Explorer', priority: 'primary', set: 'A', duration: '8–12 nights', countries: 'Botswana', seasonality: 'May–October', category: 'classic', experienceDescription: 'Botswana\'s finest camps on a private basis — exclusive-use options where available, private vehicle and guide guaranteed, helicopter transfers between camps. The pinnacle of safari exclusivity.', propertyGuidance: 'Camps offering exclusive-use or private guide guarantees. Helicopter transfers. Mix of Delta water and dry-land safari.', seoKeywords: 'luxury botswana safari, private botswana safari' },
  { number: 25, name: 'Big Cat Photography: Tanzania', priority: 'primary', set: 'A', duration: '8–12 nights', countries: 'Tanzania', seasonality: 'Jun–Oct', category: 'photography', experienceDescription: 'Designed for serious photographers — extended time in prime big cat territory, modified vehicles with camera mounts, expert photography guides. Serengeti\'s big cat prides and Ngorongoro\'s density.', propertyGuidance: 'Properties with photography-specific vehicles and guides. Camps in prime predator territory.', seoKeywords: 'photography safari tanzania, big cat safari africa' },
  { number: 27, name: 'Classic Tanzania Safari', priority: 'secondary', set: 'A', duration: '7–10 nights', countries: 'Tanzania', seasonality: 'Jun–Oct, Dec–Mar', category: 'classic', experienceDescription: 'The essential Tanzania — Serengeti, Ngorongoro Crater, Tarangire. The landscapes and wildlife concentrations that define East African safari.', propertyGuidance: 'Proven luxury lodges in each park. Balance accessibility with exclusivity.', seoKeywords: '' },
  { number: 29, name: 'Classic Kenya Safari', priority: 'secondary', set: 'A', duration: '7–10 nights', countries: 'Kenya', seasonality: 'Jul–Oct, Dec–Mar', category: 'classic', experienceDescription: 'Kenya\'s greatest hits — Masai Mara, Amboseli, Laikipia. Big Five, flamingos, Mount Kilimanjaro views, and the warmth of Kenyan hospitality.', propertyGuidance: 'Mix of private conservancy and national park properties. At least one conservancy for walking and night drives.', seoKeywords: '' },
  { number: 31, name: 'Kruger & Sabi Sands Classic', priority: 'secondary', set: 'A', duration: '5–8 nights', countries: 'South Africa', seasonality: 'May–October', category: 'classic', experienceDescription: 'South Africa\'s premier Big Five destination — the private Sabi Sands reserve bordering Kruger. Exceptional leopard sightings, walking safaris, and sophisticated lodge experiences.', propertyGuidance: 'Top-tier Sabi Sands lodges. Consider adding Kruger camp for contrast.', seoKeywords: '' },
  { number: 33, name: 'Rwanda Complete', priority: 'secondary', set: 'A', duration: '7–10 nights', countries: 'Rwanda', seasonality: 'Year-round', category: 'gorilla_primate', experienceDescription: 'Everything Rwanda offers — gorillas, golden monkeys, chimpanzees in Nyungwe, Akagera savanna game drives, and Kigali cultural immersion. The full spectrum of this remarkable country.', propertyGuidance: 'Best available in each location. Rwanda has limited ultra-luxury outside Volcanoes NP.', seoKeywords: '' },
  { number: 35, name: 'Victoria Falls & Hwange', priority: 'secondary', set: 'A', duration: '6–9 nights', countries: 'Zimbabwe', seasonality: 'May–October', category: 'classic', experienceDescription: 'Zimbabwe\'s finest — Victoria Falls spectacle combined with Hwange\'s elephant herds and diverse wildlife. Walking safaris with armed guides. Remote wilderness feel.', propertyGuidance: 'Luxury falls hotel plus premium Hwange camp. Consider adding Mana Pools if duration allows.', seoKeywords: '' },
  { number: 37, name: 'South Africa First-Timer', priority: 'secondary', set: 'A', duration: '10–14 nights', countries: 'South Africa', seasonality: 'Year-round', category: 'classic', experienceDescription: 'The complete South Africa introduction — Cape Town, Winelands, Garden Route, and a Big Five safari. Combines culture, cuisine, scenery, and wildlife in one country.', propertyGuidance: 'Boutique Cape Town hotel, wine estate, Garden Route lodge, and premium safari lodge.', seoKeywords: '' },
  { number: 39, name: 'East Africa Grand Safari', priority: 'secondary', set: 'A', duration: '14–21 nights', countries: 'Tanzania, Kenya, Rwanda', seasonality: 'Jun–Oct', category: 'multi_country', experienceDescription: 'The grand tour of East Africa — Tanzania\'s Serengeti and Ngorongoro, Kenya\'s Masai Mara and Laikipia, Rwanda\'s gorillas. The most comprehensive East African experience possible.', propertyGuidance: 'Top-tier properties in each country. Internal flights between regions. Diverse lodge styles for variety.', seoKeywords: '' },
  { number: 41, name: 'Cape to Delta', priority: 'secondary', set: 'A', duration: '12–16 nights', countries: 'South Africa, Botswana', seasonality: 'May–October', category: 'multi_country', experienceDescription: 'Two of Africa\'s finest destinations — Cape Town\'s cosmopolitan culture and Botswana\'s pristine wilderness. From vineyard lunches to mokoro rides. Dramatic contrast.', propertyGuidance: 'Boutique Cape Town and Winelands properties, then premium Delta camps.', seoKeywords: '' },
  { number: 43, name: 'Kenya & Uganda', priority: 'secondary', set: 'A', duration: '10–14 nights', countries: 'Kenya, Uganda', seasonality: 'Jun–Oct, Dec–Feb', category: 'multi_country', experienceDescription: 'Savanna wildlife and mountain gorillas — Kenya\'s big cats and plains game followed by Uganda\'s primates. Two very different African experiences in one journey.', propertyGuidance: 'Premium Kenya conservancy camps plus best available Uganda gorilla lodges.', seoKeywords: '' },
  { number: 45, name: 'Gorilla & Beach', priority: 'secondary', set: 'A', duration: '8–12 nights', countries: 'Rwanda, Tanzania', seasonality: 'Year-round (gorilla), year-round (beach)', category: 'multi_country', experienceDescription: 'Mountain gorillas in Rwanda\'s cloud forests followed by Indian Ocean relaxation. From misty volcanic highlands to turquoise waters. Unique combination of adventure and rest.', propertyGuidance: 'Ultra-luxury gorilla lodge followed by exclusive beach property in Zanzibar or mainland Tanzania coast.', seoKeywords: '' },
  { number: 47, name: 'Zambia & Zimbabwe: Falls to Bush', priority: 'secondary', set: 'A', duration: '8–12 nights', countries: 'Zambia, Zimbabwe', seasonality: 'May–October', category: 'multi_country', experienceDescription: 'Victoria Falls as the gateway to two incredible safari countries. Lower Zambezi canoe safaris, South Luangwa walking safaris, Hwange\'s elephant herds. Authentic, uncrowded wilderness.', propertyGuidance: 'Falls accommodation, then a combination of Zambian and Zimbabwean bush camps.', seoKeywords: '' },
  { number: 49, name: 'The Africa Odyssey', priority: 'secondary', set: 'A', duration: '21–28 nights', countries: 'South Africa, Botswana, Tanzania, Rwanda', seasonality: 'Jun–Oct', category: 'multi_country', experienceDescription: 'The ultimate African journey — four countries, every major ecosystem, all iconic wildlife encounters. Cape Town to Okavango to Serengeti to gorillas. For those who want it all.', propertyGuidance: 'The absolute best property in each location. This is the flagship itinerary — no compromises.', seoKeywords: '' },
  { number: 51, name: 'Chimpanzee Safari: Mahale Mountains', priority: 'secondary', set: 'A', duration: '7–10 nights', countries: 'Tanzania', seasonality: 'Jul–Oct', category: 'specialist', experienceDescription: 'One of Africa\'s most remote and exclusive wildlife encounters — habituated chimpanzees on the shores of Lake Tanganyika. Combined with Serengeti or Ruaha for variety.', propertyGuidance: 'Greystoke Mahale or equivalent. Add a contrasting savanna camp.', seoKeywords: '' },
  { number: 53, name: 'Conservation Safari', priority: 'secondary', set: 'A', duration: '8–12 nights', countries: 'Multiple', seasonality: 'Year-round', category: 'conservation', experienceDescription: 'Behind the scenes of African conservation — anti-poaching operations, wildlife research, community projects, rewilding programs. For guests who want to understand and support conservation.', propertyGuidance: 'Properties with genuine conservation programs (not greenwashing). Designer\'s choice of country based on strongest conservation stories.', seoKeywords: '' },
  { number: 55, name: 'Safari & Spa Retreat', priority: 'secondary', set: 'A', duration: '7–10 nights', countries: 'South Africa or Botswana', seasonality: 'Year-round', category: 'specialist', experienceDescription: 'Wildlife and wellness combined — morning game drives, afternoon spa treatments. For those who want safari adventure balanced with genuine relaxation and self-care.', propertyGuidance: 'Lodges with exceptional spa facilities. South Africa (Sabi Sands) or Botswana offer the best options.', seoKeywords: '' },
  { number: 57, name: 'Slow Safari: Single Lodge', priority: 'secondary', set: 'A', duration: '5–7 nights', countries: 'Designer\'s choice', seasonality: 'Year-round', category: 'specialist', experienceDescription: 'Anti-itinerary — one exceptional lodge, deep immersion, no rushing. Walking, game drives, fishing, star-gazing, conversations with guides. For those who prefer depth over breadth.', propertyGuidance: 'A single outstanding property with enough activities for a week. Guides who become friends. Designer selects the best option.', seoKeywords: '' },
  { number: 59, name: 'Cultural Immersion Safari', priority: 'secondary', set: 'A', duration: '10–14 nights', countries: 'Kenya, Tanzania', seasonality: 'Year-round', category: 'specialist', experienceDescription: 'Safari combined with authentic cultural encounters — Maasai homesteads, Hadzabe hunter-gatherer walks, Samburu ceremonies. Understanding Africa through its people as well as its wildlife.', propertyGuidance: 'Community-connected properties with genuine (not performative) cultural access.', seoKeywords: '' },
  { number: 61, name: 'Malaria-Free Family Safari', priority: 'secondary', set: 'A', duration: '5–8 nights', countries: 'South Africa', seasonality: 'Year-round', category: 'family', experienceDescription: 'Big Five safari without malaria risk — perfect for families with young children. Eastern Cape or Madikwe reserves. Full wildlife experience with peace of mind.', propertyGuidance: 'Family-friendly lodges in malaria-free reserves. Dedicated kids programs, family suites.', seoKeywords: '' },
  { number: 63, name: 'Mozambique Beach & Island', priority: 'secondary', set: 'A', duration: '5–8 nights', countries: 'Mozambique', seasonality: 'May–November', category: 'beach', experienceDescription: 'East Africa\'s most exclusive beach destination — Bazaruto Archipelago or Quirimbas. Dhow sailing, world-class diving and snorkeling, pristine beaches, seafood cuisine.', propertyGuidance: 'Island lodge or exclusive beach property. Dive/snorkel program essential.', seoKeywords: '' },
  { number: 65, name: 'Kigali City & Gorillas', priority: 'secondary', set: 'A', duration: '4–5 nights', countries: 'Rwanda', seasonality: 'Year-round', category: 'gorilla_primate', experienceDescription: 'Short but powerful — Kigali\'s Genocide Memorial and cultural scene followed by mountain gorilla trekking. For time-pressed travelers who want the essential Rwanda experience.', propertyGuidance: 'Boutique Kigali hotel plus premium gorilla lodge. Quality over duration.', seoKeywords: '' },
  { number: 67, name: 'Green Season Botswana', priority: 'secondary', set: 'A', duration: '7–10 nights', countries: 'Botswana', seasonality: 'November–March', category: 'specialist', experienceDescription: 'Botswana\'s secret season — dramatic skies, baby animals, migratory birds, zebra migration in the Makgadikgadi. Lower rates, fewer tourists, different but equally spectacular wildlife.', propertyGuidance: 'Camps that shine in green season — Kalahari, Makgadikgadi, southern Delta.', seoKeywords: '' },
  { number: 69, name: 'Tanzania Fly-In Safari', priority: 'secondary', set: 'A', duration: '7–10 nights', countries: 'Tanzania', seasonality: 'Jun–Oct', category: 'classic', experienceDescription: 'Tanzania by light aircraft — hopping between remote airstrips, covering more ground without long drives. Ruaha, Selous/Nyerere, Serengeti. The safari for those who value time.', propertyGuidance: 'Camps accessible by charter flight. Remote, low-density areas. Mix of northern and southern circuit.', seoKeywords: '' },
  { number: 71, name: 'Zanzibar & Serengeti', priority: 'secondary', set: 'A', duration: '8–12 nights', countries: 'Tanzania', seasonality: 'Jun–Oct (Serengeti), year-round (Zanzibar)', category: 'classic', experienceDescription: 'East Africa\'s classic bush-and-beach — Serengeti wildlife followed by Zanzibar\'s spice markets, Stone Town, and Indian Ocean beaches. The definitive Tanzania combination.', propertyGuidance: 'Premium Serengeti camp plus exclusive Zanzibar property. Avoid mass-tourism beach hotels.', seoKeywords: '' },
  { number: 73, name: 'Kenya Conservancy Experience', priority: 'secondary', set: 'A', duration: '7–10 nights', countries: 'Kenya', seasonality: 'Jul–Oct, Dec–Mar', category: 'classic', experienceDescription: 'Kenya\'s private conservancies — where safari meets conservation. Night drives, walking safaris, community visits. The activities forbidden in national parks. Multiple conservancy areas.', propertyGuidance: 'Conservancy-based camps in different ecosystems — Mara, Laikipia, Samburu.', seoKeywords: '' },
  { number: 75, name: 'Amboseli & Masai Mara Classic', priority: 'secondary', set: 'A', duration: '7–10 nights', countries: 'Kenya', seasonality: 'Jul–Oct', category: 'classic', experienceDescription: 'Kenya\'s two most iconic landscapes — Kilimanjaro-backdrop elephants in Amboseli and the sweeping Mara plains. Classic Kenya at its finest.', propertyGuidance: 'Premium Amboseli lodge plus Mara conservancy camp. Internal flight connection.', seoKeywords: '' },
  { number: 77, name: 'Central Kalahari & Makgadikgadi', priority: 'secondary', set: 'A', duration: '6–9 nights', countries: 'Botswana', seasonality: 'Dec–April (green), May–Oct (dry)', category: 'specialist', experienceDescription: 'Botswana beyond the Delta — vast desert landscapes, San Bushmen culture, meerkat encounters, zebra migration. A completely different Botswana experience.', propertyGuidance: 'Specialist desert camps. Properties with San cultural experiences.', seoKeywords: '' },
  { number: 79, name: 'Kenya Walking & Camel Safari', priority: 'secondary', set: 'A', duration: '7–10 nights', countries: 'Kenya', seasonality: 'Jun–Oct', category: 'walking', experienceDescription: 'Safari on foot and by camel — Laikipia and northern Kenya exploration. Mobile fly-camps, walking with armed guides, camel-supported wilderness treks. Adventure safari at its purest.', propertyGuidance: 'Properties offering walking and camel safari programs. Laikipia and Samburu specialists.', seoKeywords: '' },

  // === SET B (even numbers) ===
  { number: 2, name: 'Calving Season Safari', priority: 'primary', set: 'B', duration: '7–10 nights', countries: 'Tanzania', seasonality: 'January–March', category: 'migration', experienceDescription: 'The migration\'s most tender chapter — 8,000 calves born daily on the southern Serengeti plains. Predator action at its peak as lions, cheetahs, and hyenas exploit the abundance.', propertyGuidance: 'Ndutu area camps with direct plains access. Mobile camps that follow the herds.', seoKeywords: 'calving season serengeti, tanzania calving safari' },
  { number: 4, name: 'Private Migration Mobile Camp', priority: 'primary', set: 'B', duration: '7–10 nights', countries: 'Tanzania', seasonality: 'Jun–Oct', category: 'migration', experienceDescription: 'Private mobile camp that moves with the migration — your own camp, your own guide, your own schedule. The most exclusive way to experience the great migration.', propertyGuidance: 'Operators offering private mobile camping in the Serengeti ecosystem. Maximum exclusivity.', seoKeywords: 'private mobile safari, exclusive migration camp' },
  { number: 6, name: 'First Great Migration Safari', priority: 'primary', set: 'B', duration: '7–10 nights', countries: 'Tanzania', seasonality: 'Jun–Oct', category: 'migration', experienceDescription: 'A curated first migration experience — not overwhelming, perfectly paced, with expert guiding to interpret every moment. Designed for those experiencing the migration for the first time.', propertyGuidance: 'Accessible luxury camps with excellent guides. Not too remote — comfort matters for first-timers.', seoKeywords: 'first safari africa, migration safari for beginners' },
  { number: 8, name: 'Uganda Gorilla Explorer', priority: 'primary', set: 'B', duration: '6–9 nights', countries: 'Uganda', seasonality: 'Jun–Sep, Dec–Feb', category: 'gorilla_primate', experienceDescription: 'Uganda\'s gorilla experience — Bwindi Impenetrable Forest, potentially less crowded than Rwanda, combined with Queen Elizabeth NP for savanna wildlife and tree-climbing lions.', propertyGuidance: 'Best available Bwindi lodges plus Queen Elizabeth accommodation. Uganda has fewer luxury options than Rwanda.', seoKeywords: 'uganda gorilla safari, bwindi gorilla trekking' },
  { number: 10, name: 'Gorillas & Great Migration', priority: 'primary', set: 'B', duration: '10–14 nights', countries: 'Tanzania, Rwanda', seasonality: 'Jun–Oct', category: 'multi_country', experienceDescription: 'Africa\'s two most extraordinary wildlife experiences in one journey — mountain gorillas in Rwanda and the great migration in the Serengeti. Two completely different encounters.', propertyGuidance: 'Premium gorilla lodge plus top Serengeti camp. Charter flight connection between countries.', seoKeywords: 'gorilla and migration safari, rwanda tanzania safari' },
  { number: 12, name: 'Safari & Zanzibar Honeymoon', priority: 'primary', set: 'B', duration: '10–14 nights', countries: 'Tanzania', seasonality: 'Jun–Oct (safari), year-round (Zanzibar)', category: 'honeymoon', experienceDescription: 'The classic honeymoon combination — Serengeti or Ngorongoro wildlife followed by Zanzibar\'s spice island romance. Bush sundowners to beach sunsets.', propertyGuidance: 'Romantic safari camp (private decks, outdoor showers) followed by intimate Zanzibar boutique hotel.', seoKeywords: 'safari zanzibar honeymoon, tanzania honeymoon' },
  { number: 14, name: 'South Africa Romance: Safari & Cape Town', priority: 'primary', set: 'B', duration: '10–14 nights', countries: 'South Africa', seasonality: 'Year-round', category: 'honeymoon', experienceDescription: 'South African romance — Cape Town\'s Table Mountain and waterfront, Winelands estate dinners, then a private Big Five safari. Wine, wildlife, and world-class dining.', propertyGuidance: 'Boutique Cape Town hotel, luxury wine estate, premium Sabi Sands or Kruger lodge with honeymoon suite.', seoKeywords: 'south africa honeymoon, safari and cape town honeymoon' },
  { number: 16, name: 'Multi-Generation Family South Africa', priority: 'primary', set: 'B', duration: '10–14 nights', countries: 'South Africa', seasonality: 'Year-round', category: 'family', experienceDescription: 'South Africa for the whole family — grandparents, parents, children. Cape Town sightseeing, whale watching, a malaria-free safari. Activities for every age and fitness level.', propertyGuidance: 'Spacious family villas/suites. Malaria-free safari option. Properties with varied activity levels.', seoKeywords: 'multi generation safari, family south africa trip' },
  { number: 18, name: 'Botswana Family Safari', priority: 'primary', set: 'B', duration: '8–10 nights', countries: 'Botswana', seasonality: 'May–October', category: 'family', experienceDescription: 'Botswana for families — mokoro rides, bush walks sized for kids, junior ranger programs, splash pools. The Delta\'s water safari is naturally engaging for children.', propertyGuidance: 'Family-friendly Delta camps with minimum age of 6-8. Properties with dedicated family programming.', seoKeywords: 'botswana family safari, okavango delta family' },
  { number: 20, name: 'Okavango Delta Immersion', priority: 'primary', set: 'B', duration: '7–10 nights', countries: 'Botswana', seasonality: 'May–October', category: 'classic', experienceDescription: 'Deep Delta exploration — water camps, island camps, mokoro and motorboat, walking safaris, fishing. Three contrasting camps for the full Delta spectrum.', propertyGuidance: 'Three different Delta camps — one water-focused, one land-focused, one mixed. All premium.', seoKeywords: 'okavango delta safari, botswana delta luxury' },
  { number: 22, name: 'Ultimate Botswana: Delta to Desert', priority: 'primary', set: 'B', duration: '10–14 nights', countries: 'Botswana', seasonality: 'May–October', category: 'classic', experienceDescription: 'Botswana\'s full spectrum — lush Okavango Delta, elephant-dense Chobe, and the stark beauty of the Kalahari or Makgadikgadi salt pans. Three dramatically different landscapes.', propertyGuidance: 'Premium camps in each ecosystem. Charter flights between locations. Mix of intimate and larger properties.', seoKeywords: 'ultimate botswana safari, delta to desert safari' },
  { number: 24, name: 'Masai Mara Photography Safari', priority: 'primary', set: 'B', duration: '7–10 nights', countries: 'Kenya', seasonality: 'Jul–Oct', category: 'photography', experienceDescription: 'The Masai Mara through a lens — extended game drives in golden light, balloon photography, specialized vehicles with bean bags and camera mounts. Expert photography guides.', propertyGuidance: 'Camps with photography-specific vehicles and guides. Private conservancy for exclusive access and flexible drive times.', seoKeywords: 'masai mara photography safari, kenya photography safari' },
  { number: 26, name: 'Desert Photography: Namibia', priority: 'primary', set: 'B', duration: '10–14 nights', countries: 'Namibia', seasonality: 'Year-round (May–Oct optimal)', category: 'photography', experienceDescription: 'Namibia\'s otherworldly landscapes for photographers — Sossusvlei dunes, Deadvlei, Skeleton Coast, Etosha\'s waterholes. Dramatic light, stark contrasts, wildlife silhouettes.', propertyGuidance: 'Lodges positioned for optimal photography light. Mix of luxury lodges and tented camps.', seoKeywords: 'namibia photography safari, desert photography tour' },
  { number: 28, name: 'Southern Tanzania Wilderness', priority: 'secondary', set: 'B', duration: '7–10 nights', countries: 'Tanzania', seasonality: 'Jun–Oct', category: 'classic', experienceDescription: 'Tanzania beyond the crowds — Ruaha, Nyerere (Selous), and the remote southern parks. Wild dog territory, boat safaris, walking safaris. Authentic wilderness without the tourist circuit.', propertyGuidance: 'Remote camps in southern circuit. Properties that emphasize walking and water safaris.', seoKeywords: '' },
  { number: 30, name: 'Laikipia & Samburu Explorer', priority: 'secondary', set: 'B', duration: '7–10 nights', countries: 'Kenya', seasonality: 'Jul–Oct, Dec–Mar', category: 'classic', experienceDescription: 'Northern Kenya\'s unique wildlife — Samburu specials (Grevy\'s zebra, reticulated giraffe, gerenuk), Laikipia conservancy walking safaris, camel encounters. Kenya beyond the Mara.', propertyGuidance: 'Premium Laikipia conservancy camp plus Samburu lodge. Properties with strong conservation stories.', seoKeywords: '' },
  { number: 32, name: 'Cape Town & Safari', priority: 'secondary', set: 'B', duration: '8–12 nights', countries: 'South Africa', seasonality: 'Year-round', category: 'classic', experienceDescription: 'South Africa\'s greatest hits — Table Mountain, Cape Peninsula, Winelands, then Big Five safari. The perfect introduction to South Africa.', propertyGuidance: 'Boutique Cape Town, wine estate, premium safari lodge. Fly between Cape Town and safari.', seoKeywords: '' },
  { number: 34, name: 'Classic Namibia', priority: 'secondary', set: 'B', duration: '10–14 nights', countries: 'Namibia', seasonality: 'May–October', category: 'classic', experienceDescription: 'Namibia\'s iconic circuit — Sossusvlei dunes, Damaraland desert elephants, Etosha National Park, Skeleton Coast. Vast landscapes, sparse population, otherworldly beauty.', propertyGuidance: 'Mix of luxury lodges and tented camps. Self-drive option for adventurous clients, otherwise fly-in.', seoKeywords: '' },
  { number: 36, name: 'Lower Zambezi & South Luangwa', priority: 'secondary', set: 'B', duration: '7–10 nights', countries: 'Zambia', seasonality: 'May–October', category: 'classic', experienceDescription: 'Zambia\'s two finest parks — Lower Zambezi canoe safaris and South Luangwa walking safaris. Authentic, uncrowded, guided by some of Africa\'s best safari guides.', propertyGuidance: 'Premium camps in both parks. Properties known for guide quality.', seoKeywords: '' },
  { number: 38, name: 'Chobe River Safari', priority: 'secondary', set: 'B', duration: '4–6 nights', countries: 'Botswana', seasonality: 'May–October', category: 'classic', experienceDescription: 'Chobe\'s riverside spectacle — 50,000 elephants, massive buffalo herds, and predator action along the Chobe River. Boat safaris at sunset. Can combine with Victoria Falls.', propertyGuidance: 'Riverfront lodge or houseboat. Boat safari essential.', seoKeywords: '' },
  { number: 40, name: 'Southern Africa Complete', priority: 'secondary', set: 'B', duration: '14–21 nights', countries: 'Botswana, Zimbabwe, Zambia', seasonality: 'May–October', category: 'multi_country', experienceDescription: 'The complete southern Africa circuit — Okavango Delta, Victoria Falls, Lower Zambezi or South Luangwa, Hwange. Three countries, diverse ecosystems, every major experience.', propertyGuidance: 'Top properties in each country. Charter connections between remote camps.', seoKeywords: '' },
  { number: 42, name: 'Tanzania & Kenya Combination', priority: 'secondary', set: 'B', duration: '10–14 nights', countries: 'Tanzania, Kenya', seasonality: 'Jun–Oct', category: 'multi_country', experienceDescription: 'The best of both East African giants — Serengeti and Ngorongoro in Tanzania, Masai Mara in Kenya. Compare the two sides of the migration ecosystem.', propertyGuidance: 'Premium camps in both countries. Cross-border charter or scheduled flight connection.', seoKeywords: '' },
  { number: 44, name: 'Botswana & Namibia: Delta to Desert', priority: 'secondary', set: 'B', duration: '12–16 nights', countries: 'Botswana, Namibia', seasonality: 'May–October', category: 'multi_country', experienceDescription: 'Two dramatically different landscapes — Botswana\'s lush waterways and Namibia\'s stark deserts. Delta wildlife and dune photography. Water and sand.', propertyGuidance: 'Premium Delta camps plus top Namibia lodges. Charter transfers.', seoKeywords: '' },
  { number: 46, name: 'South Africa & Mozambique', priority: 'secondary', set: 'B', duration: '10–14 nights', countries: 'South Africa, Mozambique', seasonality: 'May–November', category: 'multi_country', experienceDescription: 'Bush and beach in southern Africa — Big Five safari in South Africa followed by Mozambique\'s pristine Indian Ocean beaches. Diving, whale sharks, and barefoot luxury.', propertyGuidance: 'Premium South Africa safari lodge plus exclusive Mozambique island/beach property.', seoKeywords: '' },
  { number: 48, name: 'Rwanda & South Africa', priority: 'secondary', set: 'B', duration: '10–14 nights', countries: 'Rwanda, South Africa', seasonality: 'Year-round', category: 'multi_country', experienceDescription: 'Africa\'s contrasts — Rwanda\'s intimate gorilla encounters combined with South Africa\'s Big Five and Cape Town. Two completely different African experiences.', propertyGuidance: 'Ultra-luxury gorilla lodge, Cape Town boutique, premium safari lodge.', seoKeywords: '' },
  { number: 50, name: 'Namibia Luxury Fly-In', priority: 'secondary', set: 'B', duration: '8–12 nights', countries: 'Namibia', seasonality: 'Year-round', category: 'specialist', experienceDescription: 'Namibia by charter — flying between remote lodges, covering the vast distances efficiently. Skeleton Coast, Kaokoland, Sossusvlei from the air. For those who value both remoteness and comfort.', propertyGuidance: 'Fly-in luxury camps in diverse Namibian landscapes. Properties accessible only by air.', seoKeywords: '' },
  { number: 52, name: 'Tanzania Walking Safari', priority: 'secondary', set: 'B', duration: '6–10 nights', countries: 'Tanzania', seasonality: 'Jun–Oct', category: 'walking', experienceDescription: 'Tanzania on foot — walking safaris in Ruaha, Nyerere, or the Serengeti periphery. Armed ranger escorts, fly-camping, tracking wildlife by spoor. The original way to safari.', propertyGuidance: 'Camps specializing in walking safaris. Licensed walking guides essential.', seoKeywords: '' },
  { number: 54, name: 'Walking Safari Collection', priority: 'secondary', set: 'B', duration: '8–12 nights', countries: 'Zambia, Tanzania, or Kenya', seasonality: 'Jun–Oct', category: 'walking', experienceDescription: 'Africa\'s finest walking safaris collected into one itinerary — multiple walking camps across one or two countries. For experienced safari-goers who want the primal experience.', propertyGuidance: 'Walking-specialist camps. Designer selects the strongest walking destination.', seoKeywords: '' },
  { number: 56, name: 'Digital Detox Safari', priority: 'secondary', set: 'B', duration: '5–7 nights', countries: 'Botswana or Zambia', seasonality: 'May–October', category: 'specialist', experienceDescription: 'Deliberate disconnection — remote camps with no WiFi, no phone signal, no screens. Star-gazing, fire-side stories, walking safaris, genuine presence. For those who need to unplug.', propertyGuidance: 'Genuinely remote camps. Properties where disconnection is a feature, not a bug.', seoKeywords: '' },
  { number: 58, name: 'Birding Safari Tanzania', priority: 'secondary', set: 'B', duration: '10–14 nights', countries: 'Tanzania', seasonality: 'Nov–Apr (migrants present)', category: 'specialist', experienceDescription: 'Tanzania through a birder\'s eyes — 1,100+ species across diverse habitats. Serengeti raptors, forest endemics in the Eastern Arc mountains, flamingos in the Rift Valley.', propertyGuidance: 'Properties in diverse birding habitats. Guides with strong ornithological knowledge.', seoKeywords: '' },
  { number: 60, name: 'Star Bed Safari Collection', priority: 'secondary', set: 'B', duration: '7–10 nights', countries: 'Botswana, Kenya', seasonality: 'May–October', category: 'specialist', experienceDescription: 'Sleep under African skies — properties with dedicated star beds or treehouse sleep-outs. Multiple star bed experiences across different landscapes. The romance of sleeping wild.', propertyGuidance: 'Properties with permanent or semi-permanent star bed/treehouse/sleep-out options.', seoKeywords: '' },
  { number: 62, name: 'Uganda Primate & Safari', priority: 'secondary', set: 'B', duration: '8–12 nights', countries: 'Uganda', seasonality: 'Jun–Sep, Dec–Feb', category: 'gorilla_primate', experienceDescription: 'The complete Uganda — gorillas in Bwindi, chimpanzees in Kibale, tree-climbing lions in Queen Elizabeth, Murchison Falls. More variety per square mile than almost anywhere.', propertyGuidance: 'Best available lodges in each park. Uganda\'s luxury options are improving rapidly.', seoKeywords: '' },
  { number: 64, name: 'Namibia Self-Drive Adventure', priority: 'secondary', set: 'B', duration: '12–16 nights', countries: 'Namibia', seasonality: 'Year-round', category: 'specialist', experienceDescription: 'Namibia at your own pace — self-drive through empty landscapes, gravel roads stretching to the horizon. Freedom to stop wherever, stay as long as you like. For independent-minded travelers.', propertyGuidance: 'Mix of luxury lodges and remote campsites. Well-serviced route with manageable daily distances.', seoKeywords: '' },
  { number: 66, name: 'Rwanda Conservation Safari', priority: 'secondary', set: 'B', duration: '6–9 nights', countries: 'Rwanda', seasonality: 'Year-round', category: 'conservation', experienceDescription: 'Rwanda\'s conservation success story — from genocide to gorilla recovery. Visit conservation projects, understand community-based tourism, trek gorillas knowing the context. Meaningful travel.', propertyGuidance: 'Properties with genuine conservation partnerships. Community engagement essential.', seoKeywords: '' },
  { number: 68, name: 'KwaZulu-Natal Explorer', priority: 'secondary', set: 'B', duration: '7–10 nights', countries: 'South Africa', seasonality: 'Year-round', category: 'classic', experienceDescription: 'South Africa\'s most diverse province — Hluhluwe-iMfolozi (oldest game reserve in Africa), iSimangaliso wetlands, Drakensberg mountains. Wildlife, beaches, and mountains in one region.', propertyGuidance: 'Mix of game lodges, beach properties, and mountain retreats in KZN.', seoKeywords: '' },
  { number: 70, name: 'Tanzania First-Timer Explorer', priority: 'secondary', set: 'B', duration: '7–10 nights', countries: 'Tanzania', seasonality: 'Jun–Oct, Dec–Mar', category: 'classic', experienceDescription: 'Tanzania for the first time — the essential northern circuit done right. Serengeti, Ngorongoro, Tarangire. Expert guiding to interpret the experience. Not rushed, well-paced.', propertyGuidance: 'Accessible luxury lodges. Not too remote. Excellent guides who can interpret for newcomers.', seoKeywords: '' },
  { number: 72, name: 'Northern Tanzania Complete', priority: 'secondary', set: 'B', duration: '10–14 nights', countries: 'Tanzania', seasonality: 'Jun–Oct', category: 'classic', experienceDescription: 'Every highlight of northern Tanzania — Serengeti, Ngorongoro, Tarangire, Lake Manyara, and Arusha NP. Extended time in each for depth. The comprehensive northern circuit.', propertyGuidance: 'Top-tier lodges in each park. Mix of large lodges and intimate camps for variety.', seoKeywords: '' },
  { number: 74, name: 'Kenya Coast Safari & Beach', priority: 'secondary', set: 'B', duration: '8–12 nights', countries: 'Kenya', seasonality: 'Jul–Oct', category: 'beach', experienceDescription: 'Kenya\'s north coast and safari combination — Tsavo or Amboseli wildlife followed by Lamu or Diani beach. Swahili culture, dhow sailing, and safari in one journey.', propertyGuidance: 'Safari lodge plus exclusive beach/island property. Lamu for culture, Diani for beaches.', seoKeywords: '' },
  { number: 76, name: 'Makgadikgadi & Meerkats', priority: 'secondary', set: 'B', duration: '4–6 nights', countries: 'Botswana', seasonality: 'Year-round', category: 'specialist', experienceDescription: 'The salt pans experience — meerkat encounters at dawn, quad biking across the pans, sleeping under star-drenched skies. Chapman\'s Baobab and the vast nothingness of the pans.', propertyGuidance: 'Camps specializing in pan experiences with meerkat habituation programs.', seoKeywords: '' },
  { number: 78, name: 'Uganda Off-the-Beaten-Path', priority: 'secondary', set: 'B', duration: '10–14 nights', countries: 'Uganda', seasonality: 'Jun–Sep, Dec–Feb', category: 'specialist', experienceDescription: 'Uganda beyond the obvious — Kidepo Valley (one of Africa\'s most remote parks), Murchison Falls, Mount Elgon. For experienced safari travelers seeking genuine frontier.', propertyGuidance: 'Best available in each area. Some locations have limited luxury options — select the best of what exists.', seoKeywords: '' },
  { number: 80, name: 'Walking Safari Botswana', priority: 'secondary', set: 'B', duration: '5–8 nights', countries: 'Botswana', seasonality: 'May–October', category: 'walking', experienceDescription: 'Botswana on foot — walking safaris in the Okavango Delta and surrounding concessions. Island-hopping on foot, tracking big game with armed guides. The elemental Delta experience.', propertyGuidance: 'Walking-specialist camps in the Delta. Small camps, expert walking guides.', seoKeywords: '' },
]

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  for (const t of targets) {
    await db.execute(sql`
      INSERT INTO "itinerary_targets" (
        "number", "name", "priority", "set", "duration", "countries",
        "seasonality", "category", "experience_description",
        "property_guidance", "seo_keywords", "status",
        "updated_at", "created_at"
      ) VALUES (
        ${t.number}, ${t.name}, ${t.priority}, ${t.set}, ${t.duration},
        ${t.countries}, ${t.seasonality}, ${t.category},
        ${t.experienceDescription}, ${t.propertyGuidance},
        ${t.seoKeywords || null}, 'not_started',
        NOW(), NOW()
      ) ON CONFLICT ("number") DO NOTHING
    `)
  }
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`DELETE FROM "itinerary_targets" WHERE "number" BETWEEN 1 AND 80`)
}
